yes_no:
  - - '--Select--'
    - ''
  - - 'Yes'
    - 1
  - - 'No'
    - 0
reference_datasets:
  - - '--Select--'
    - ''
  - - 'Genomic Sequence'
    - 'Genomic Sequence'
  - - 'Transcript Assembly'
    - 'Transcript Assembly'
  - - 'Genome'
    - 'Genome'
  - - 'Genetic Map'
    - 'Genetic Map'
  - - 'Physical Map'
    - 'Physical Map'
  - - 'Short Read Data'
    - 'Short Read Data'
  - - 'GFF3 Annotations'
    - 'GFF3 Annotations'
  - - 'Polymorphism Data'
    - 'Polymorphism Data'
nodulation_type:
  - - '--Select--'
    - ''
  - - 'Determinate'
    - 'Determinate'
  - - 'Indeterminate'
    - 'Indeterminate'
flowering_type:
  - - '--Select--'
    - ''
  - - 'Short Day'
    - 'Short Day'
  - - 'Long Day'
    - 'Long Day'
pollination_type:
  - - '--Select--'
    - ''
  - - 'Wind'
    - 'Wind'
  - - 'Insect'
    - 'Insect'
  - - 'Self'
    - 'Self'
  - - 'Bird'
    - 'Bird'
  - - 'Bat'
    - 'Bat'
self_incompatibility:
  - - '--Select--'
    - ''
  - - 'Predominately Inbreeding'
    - 'Predominately Inbreeding'
  - - 'Predominantly Outcrossing'
    - 'Predominantly Outcrossing'
ploidy_type:
  - - '--Select--'
    - ''
  - - 'Auto'
    - 'Auto'
  - - 'Allo-Tetraploid'
    - 'Allo-Tetraploid'
